# -*- coding: utf-8 -*-
"""Deniz Balıkları Sınıflandırması

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j6yhlOJhc9TdxTPNXZ-9CGZFoZ3ii2O2
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
crowww_a_large_scale_fish_dataset_path = kagglehub.dataset_download('crowww/a-large-scale-fish-dataset')

print('Data source import complete.')

from google.colab import drive
drive.mount('/content/drive')

"""🐟**Derin Öğrenmeye Giriş: Fish Dataset ile Adım Adım Öğrenme**
Bu notebook, derin öğrenmeye sıfırdan başlayanlar ve bilgilerini geliştirmek isteyenler için hazırlanmış kapsamlı bir rehberdir. Her bölüm (PART) ayrı bir konuya odaklanır ve hem teorik açıklama hem de uygulamalı kod içerir.

🎯 *Öğrenme Hedefleri*

Derin öğrenmenin temel kavramlarını anlamak
TensorFlow/Keras ile model oluşturmayı öğrenmek
Farklı katman türlerini ve aktivasyon fonksiyonlarını keşfetmek
CNN mimarisini anlamak ve uygulamak
Transfer Learning tekniklerini öğrenmek
Model performansını optimize etmeyi öğrenmek

📌 *İçindekiler*


* PART 1: Derin Öğrenmeye Giriş & Dataset Hazırlığı
* PART 2: Dense, Flatten Katmanları ve Aktivasyon Fonksiyonlarına Giriş
* PART 3: Aktivasyon Fonksiyonlarının Karşılaştırılması
* PART 4: Loss Fonksiyonları ve Optimizasyon
* PART 5: Regularization Teknikleri
* PART 6: CNN Katmanları (Conv2D ve Pooling)
* PART 7: Transfer Learning
* PART 8: Hyperparameter Tuning

# 📖 PART 1: Derin Öğrenmeye Giriş & Dataset Hazırlığı
🤖 **Derin Öğrenme Nedir?**
Derin Öğrenme (Deep Learning), yapay zeka alanının en güçlü dallarından biridir. İnsan beynindeki nöronların çalışma prensibinden ilham alarak:

Katmanlar halinde bilgi işleme
Otomatik özellik çıkarma (Feature Extraction)
Büyük veri setlerinden kalıpları öğrenme

🎯**Temel Kavramlar:**

Nöron: Temel işlem birimi
Katman (Layer): Nöronların grubu
Ağırlık (Weight): Bağlantıların gücü
Bias: Karar eşiği
Aktivasyon: Nöronun çıkışını belirleme

🐠**Fish Dataset Hakkında**
Bu projede balık türlerini sınıflandırmak için büyük ölçekli bir balık veri seti kullanıyoruz. Dataset'in özellikleri:

Çoklu balık türleri (çeşitli deniz canlıları)
Yüksek çözünürlüklü görüntüler
Ground truth (doğru etiketler) dahil
"""

import os
# CUDA ayarlarını TensorFlow import edilmeden önce yapın
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'   # Gereksiz logları gizle
os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'
os.environ['CUDA_CACHE_DISABLE'] = '0'

# Gerekli kütüphaneleri import et
import tensorflow as tf
#tf.config.set_visible_devices([], 'GPU')  # GPU'ları gizle (CPU'da çalışır)

import matplotlib.pyplot as plt
import numpy as np
import shutil
import tempfile
from tensorflow.keras import layers, models

# Matplotlib ayarları
plt.style.use('default')
plt.rcParams['figure.figsize'] = (12, 8)
plt.rcParams['font.size'] = 10

print("🚀 Gerekli kütüphaneler yüklendi!")
print(f"TensorFlow versiyon: {tf.__version__}")

# Dataset yolu - Kaggle'daki Fish Dataset
data_dir = "../input/a-large-scale-fish-dataset/Fish_Dataset/Fish_Dataset"

def analyze_dataset_structure(data_path):
    """
    Dataset yapısını analiz eder ve rapor oluşturur
    """
    print("=" * 60)
    print("📊 VERİ SETİ YAPISI ANALİZİ")
    print("=" * 60)

    try:
        # Ana dizindeki klasörleri listele
        main_contents = os.listdir(data_path)
        species_count = len(main_contents)

        print(f"🎣 Toplam balık türü: {species_count}")
        print(f"📁 Ana dizin: {data_path}")
        print()

        total_images = 0
        species_info = {}

        for species in main_contents:
            species_path = os.path.join(data_path, species)

            if os.path.isdir(species_path):
                subfolders = os.listdir(species_path)
                print(f"🐠 {species}:")

                for subfolder in subfolders:
                    subfolder_path = os.path.join(species_path, subfolder)
                    if os.path.isdir(subfolder_path):
                        # Görsel dosyalarını say
                        image_files = [f for f in os.listdir(subfolder_path)
                                     if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp'))]
                        image_count = len(image_files)

                        if not subfolder.endswith(' GT'):  # Ground Truth klasörü değilse
                            total_images += image_count
                            species_info[species] = image_count

                        folder_type = "🖼️ Görseller" if not subfolder.endswith(' GT') else "🎯 Ground Truth"
                        print(f"    ├── {folder_type}: {image_count} dosya")

                print()

        print("=" * 60)
        print("📈 ÖZET BİLGİLER")
        print("=" * 60)
        print(f"🎯 Toplam görsel sayısı: {total_images}")
        print(f"🎣 Ortalama tür başına görsel: {total_images // species_count}")
        print(f"📊 En çok görseli olan tür: {max(species_info.items(), key=lambda x: x[1])}")
        print(f"📉 En az görseli olan tür: {min(species_info.items(), key=lambda x: x[1])}")

        return species_info, total_images

    except Exception as e:
        print(f"❌ Hata: {e}")
        return {}, 0

# Dataset analizini çalıştır
species_info, total_images = analyze_dataset_structure(data_dir)

import os
import shutil
import tempfile

# Correcting the data_dir path
# The Kaggle dataset path is provided by kagglehub in 'crowww_a_large_scale_fish_dataset_path'
# Assuming the structure is: <kagglehub_path>/Fish_Dataset/Fish_Dataset/...
data_dir = os.path.join(crowww_a_large_scale_fish_dataset_path, "Fish_Dataset", "Fish_Dataset")

def prepare_dataset_structure(source_dir):
    """
    İç içe klasör yapısını TensorFlow için uygun hale getirir

    Orijinal yapı: Fish_Dataset/BalikTuru/BalikTuru/resim.jpg
    Hedef yapı: temp_dir/BalikTuru/resim.jpg
    """
    print("🔄 Dataset yapısı düzenleniyor...")

    # Geçici dizin oluştur
    temp_dir = tempfile.mkdtemp()
    print(f"📁 Geçici dizin: {temp_dir}")

    species_dirs = [d for d in os.listdir(source_dir)
                   if os.path.isdir(os.path.join(source_dir, d))]

    total_copied = 0

    for species in species_dirs:
        species_path = os.path.join(source_dir, species)
        subfolders = os.listdir(species_path)

        # GT olmayan (görsel) klasörü bul
        image_folder = None
        for subfolder in subfolders:
            if not subfolder.endswith(' GT'):
                image_folder = subfolder
                break

        if image_folder:
            source_images = os.path.join(species_path, image_folder)
            target_species = os.path.join(temp_dir, species)

            if os.path.exists(source_images):
                # Tür klasörünü oluştur
                os.makedirs(target_species, exist_ok=True)

                # Görselleri kopyala
                copied_count = 0
                for img_file in os.listdir(source_images):
                    if img_file.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp')):
                        src = os.path.join(source_images, img_file)
                        dst = os.path.join(target_species, img_file)
                        try:
                            shutil.copy2(src, dst)
                            copied_count += 1
                        except Exception as e:
                            print(f"    ⚠️ {img_file} kopyalanamadı: {e}")

                total_copied += copied_count
                print(f"    ✅ {species}: {copied_count} görsel kopyalandı")

    print(f"🎉 Toplam {total_copied} görsel başarıyla düzenlendi!")
    return temp_dir

# Dataset yapısını düzenle
print("📁 Dataset hazırlığı başlıyor...")
processed_data_dir = prepare_dataset_structure(data_dir)

# Model parametreleri
IMG_SIZE = (128, 128)  # Görsel boyutu (daha hızlı eğitim için küçük)
BATCH_SIZE = 32        # Her seferde işlenecek görsel sayısı
VALIDATION_SPLIT = 0.2 # %20 doğrulama verisi
RANDOM_SEED = 123      # Tekrarlanabilir sonuçlar için

print("🎛️ MODEL PARAMETRELERİ")
print("=" * 40)
print(f"📐 Görsel boyutu: {IMG_SIZE}")
print(f"📦 Batch boyutu: {BATCH_SIZE}")
print(f"🎲 Validation split: {VALIDATION_SPLIT}")
print(f"🌱 Random seed: {RANDOM_SEED}")

# Eğitim veri setini oluştur
print("\n🔄 Veri setleri yükleniyor...")
tf.keras.layers.Rescaling(1./255) #Modelin daha hızlı ve doğru çalışması için renkleri basit sayılara dönüştürme

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    processed_data_dir,
    validation_split=VALIDATION_SPLIT,
    subset="training",
    seed=RANDOM_SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='int'  # Sınıf etiketleri için integer kullan
)

# Doğrulama veri setini oluştur
val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    processed_data_dir,
    validation_split=VALIDATION_SPLIT,
    subset="validation",
    seed=RANDOM_SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='int'
)

# Sınıf bilgileri
class_names = train_ds.class_names
num_classes = len(class_names)

print(f"✅ Veri setleri hazır!")
print(f"🏷️ Bulunan sınıflar ({num_classes} adet):")
for i, class_name in enumerate(class_names):
    print(f"    {i}: {class_name}")

# Veri setinden örnek görseller göster
def display_sample_images(dataset, class_names, num_samples=9):
    """
    Veri setinden örnek görselleri gösterir
    """
    plt.figure(figsize=(15, 15))

    # İlk batch'i al
    for images, labels in dataset.take(1):
        # Gösterilecek örnek sayısını belirle
        samples_to_show = min(num_samples, len(images))

        # Grid boyutunu hesapla
        grid_size = int(np.ceil(np.sqrt(samples_to_show)))

        for i in range(samples_to_show):
            ax = plt.subplot(grid_size, grid_size, i + 1)

            # Görseli göster
            image = images[i].numpy().astype("uint8")
            plt.imshow(image)

            # Sınıf etiketi ekle
            label_index = labels[i].numpy()
            if label_index < len(class_names):
                title = f"{class_names[label_index]}"
                plt.title(title, fontsize=12, pad=10)
            else:
                plt.title(f"Label: {label_index}", fontsize=12, pad=10)

            plt.axis("off")

    plt.tight_layout()
    plt.suptitle("🖼️ Örnek Görüntüler", fontsize=16, y=1.02)
    plt.show()

# Örnek görselleri göster
print("🖼️ Örnek görüntüler yükleniyor...")
display_sample_images(train_ds, class_names, num_samples=12)

# Veri seti performansını optimize et
print("⚡ Veri seti performansı optimize ediliyor...")

AUTOTUNE = tf.data.AUTOTUNE

# Cache ve prefetch ile performansı artır
train_ds = train_ds.cache().prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

print("✅ Veri setleri optimize edildi!")
print(f"🚀 Eğitim seti batch sayısı: {len(train_ds)}")
print(f"🎯 Doğrulama seti batch sayısı: {len(val_ds)}")
print(f"📊 Tahmini eğitim görsel sayısı: {len(train_ds) * BATCH_SIZE}")
print(f"📊 Tahmini doğrulama görsel sayısı: {len(val_ds) * BATCH_SIZE}")

"""# 📖 PART 2: Dense, Flatten Katmanları ve Aktivasyon Fonksiyonlarına Giriş
🧠 **Temel Katman Türleri**
1. *Dense Layer (Tam Bağlantılı Katman)*

Her nöronun önceki katmandaki tüm nöronlarla bağlantılı olduğu katman

* Parametre sayısı: **(input_size × output_size) + bias_terms**

* Kullanım alanı: Sınıflandırma ve regresyon problemlerinin son katmanları

2. *Flatten Layer*
   
Bilgisayarın görsel matrisini (en, boy, renk kanalı) alıp, Dense katmanının anlayacağı şekilde tek, uzun bir çizgi (vektör) haline getirir.

Çok boyutlu veriyi (örn: 28×28×3) tek boyutlu vektöre (2352,) çevirir

* Parametre yok - sadece veri formatını değiştirir

* CNN'den Dense'e geçişte zorunlu

3. *Aktivasyon Fonksiyonları*
Neural network'lerin doğrusal olmayan kararlar almasını sağlar:


* ReLU: max(0, x) - En popüler, hızlı hesaplama

* Sigmoid: 1/(1+e^(-x)) - 0-1 arası çıkış, binary sınıflandırma

* Softmax: Çoklu sınıf olasılıkları, toplamları 1 (tahmin edilen tüm balık türlerinin olasılıklarını toplayıp 1 yapacak şekilde dağıtması)

* Tanh: -1 ile 1 arası çıkış, sıfır merkezli
"""

print("🏗️ İLK NEURAL NETWORK MODELİ OLUŞTURULUYOR")
print("=" * 60)

def create_simple_model(input_shape, num_classes, hidden_units=128):
    """
    Basit Dense katmanlı model oluşturur

    Mimari: Input -> Flatten -> Dense(ReLU) -> Dense(Softmax)
    """
    model = models.Sequential([
        # Giriş katmanı - görsel boyutunu belirt
        layers.Input(shape=input_shape),

        # Veri normalleştirme - piksel değerlerini 0-1 arasına çek
        layers.Rescaling(1./255, name="normalization"),

        # Çok boyutlu görüntüyü 1D vektöre çevir
        layers.Flatten(name="flatten"),

        # Gizli katman - özellik öğrenme
        layers.Dense(hidden_units, activation='relu', name="hidden_layer"),

        # Çıkış katmanı - sınıf olasılıkları
        layers.Dense(num_classes, activation='softmax', name="output_layer")
    ], name="SimpleNeuralNetwork")

    return model

# Model oluştur
simple_model = create_simple_model(
    input_shape=IMG_SIZE + (3,),  # RGB görseller için (128, 128, 3)
    num_classes=num_classes,
    hidden_units=128
)

# Model özetini göster
print("📋 MODEL MİMARİSİ:")
simple_model.summary()

# Model yapısını görselleştir (opsiyonel)
print(f"\n🔍 MODEL DETAYLARI:")
print(f"   📐 Giriş boyutu: {IMG_SIZE + (3,)}")
print(f"   🎯 Sınıf sayısı: {num_classes}")
print(f"   🧠 Gizli katman nöron sayısı: 128")
print(f"   📊 Toplam parametre sayısı: {simple_model.count_params():,}")

# Modeli derleme (Compile)
print("⚙️ MODEL DERLENİYOR...")

# Optimizasyon ayarları
LEARNING_RATE = 0.001
OPTIMIZER = tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE)
LOSS_FUNCTION = 'sparse_categorical_crossentropy'  # Integer etiketler için
METRICS = ['accuracy']

simple_model.compile(
    optimizer=OPTIMIZER,
    loss=LOSS_FUNCTION,
    metrics=METRICS
)

print("✅ Model başarıyla derlendi!")
print(f"🎯 Optimizer: Adam (lr={LEARNING_RATE})")
print(f"📉 Loss fonksiyonu: {LOSS_FUNCTION}")
print(f"📊 Metrikler: {METRICS}")

# Model eğitimi
print("🚀 MODEL EĞİTİMİ BAŞLIYOR...")
print("=" * 50)

# Eğitim parametreleri
EPOCHS = 5  # Hızlı test için az epoch
VERBOSE = 1  # Eğitim durumunu göster

# Early stopping callback (opsiyonel - overfitting'i önler)
early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True,
    verbose=1
)

# Model checkpoint (en iyi modeli kaydet)
checkpoint = tf.keras.callbacks.ModelCheckpoint(
    'best_simple_model.h5',
    monitor='val_accuracy',
    save_best_only=True,
    verbose=1
)

print(f"📚 Epoch sayısı: {EPOCHS}")
print(f"⏰ Tahmini süre: ~{EPOCHS * 2} dakika")
print()

# Eğitimi başlat
import time
start_time = time.time()

history = simple_model.fit(
    train_ds,
    epochs=EPOCHS,
    validation_data=val_ds,
    callbacks=[early_stopping],  # checkpoint kaldırıldı (dosya sistemi kısıtlaması)
    verbose=VERBOSE
)

end_time = time.time()
training_time = end_time - start_time

print(f"\n✅ EĞİTİM TAMAMLANDI!")
print(f"⏱️ Toplam süre: {training_time:.2f} saniye")
print(f"⏱️ Epoch başına ortalama: {training_time/EPOCHS:.2f} saniye")

# Eğitim sonuçlarını görselleştir
def plot_training_history(history, title="Model Eğitim Sonuçları"):
    """
    Eğitim geçmişini görselleştirir
    """
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

    epochs_range = range(1, len(history.history['accuracy']) + 1)

    # Accuracy grafiği
    ax1.plot(epochs_range, history.history['accuracy'], 'b-',
             label='Eğitim Doğruluğu', linewidth=2, marker='o')
    ax1.plot(epochs_range, history.history['val_accuracy'], 'r-',
             label='Doğrulama Doğruluğu', linewidth=2, marker='s')

    ax1.set_title('Model Doğruluğu', fontsize=14, fontweight='bold')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Doğruluk')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    ax1.set_ylim(0, 1)

    # Loss grafiği
    ax2.plot(epochs_range, history.history['loss'], 'b-',
             label='Eğitim Kaybı', linewidth=2, marker='o')
    ax2.plot(epochs_range, history.history['val_loss'], 'r-',
             label='Doğrulama Kaybı', linewidth=2, marker='s')

    ax2.set_title('Model Kaybı', fontsize=14, fontweight='bold')
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Kayıp')
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    plt.suptitle(title, fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.show()

# Eğitim geçmişini görselleştir
plot_training_history(history, "🎯 Basit Neural Network Sonuçları")

# Final performans metrikleri
final_train_acc = history.history['accuracy'][-1]
final_val_acc = history.history['val_accuracy'][-1]
final_train_loss = history.history['loss'][-1]
final_val_loss = history.history['val_loss'][-1]

print("📊 FINAL PERFORMANS")
print("=" * 40)
print(f"🎯 Eğitim Doğruluğu: %{final_train_acc*100:.2f}")
print(f"🎯 Doğrulama Doğruluğu: %{final_val_acc*100:.2f}")
print(f"📉 Eğitim Kaybı: {final_train_loss:.4f}")
print(f"📉 Doğrulama Kaybı: {final_val_loss:.4f}")

# Overfitting kontrolü
accuracy_gap = abs(final_train_acc - final_val_acc)
if accuracy_gap > 0.15:
    print(f"⚠️ OVERFITTING RİSKİ VAR (Fark: %{accuracy_gap*100:.2f})")
    print("   💡 Çözüm önerileri: Dropout, daha az epoch, daha az parametre")
elif accuracy_gap > 0.05:
    print(f"⚡ HAFİF OVERFITTING (Fark: %{accuracy_gap*100:.2f})")
    print("   💡 Normal seviyede, endişelenmeyin")
else:
    print("✅ MODEL DENGELİ GÖRÜNÜYOR")
    print("   🎉 Eğitim ve doğrulama performansı uyumlu")

"""# 📖 PART 3: Aktivasyon Fonksiyonlarının Karşılaştırılması

Aktivasyon fonksiyonları:Bu fonksiyonlar olmasaydı, modelimiz ne kadar katmandan oluşursa oluşsun sadece düz bir çizgi çizebilirdi. Balık gibi karmaşık şekilleri öğrenmesi için, modelin bu 'bükülme' yeteneğine ihtiyacı var.

- **Sigmoid:** 0–1 arası değer döndürür.
- **Tanh:** -1 ile 1 arası değer döndürür.
- **ReLU:** Negatifleri sıfırlar, pozitifleri aynen geçirir.
- **Leaky ReLU:** ReLU’nun geliştirilmiş hali, negatiflere küçük değerler bırakır.

Aynı mimariyi farklı aktivasyonlarla çalıştırıp sonuçları karşılaştıracağız.
"""

import time
from tensorflow.keras import backend as K

def create_activation_test_model(activation, input_shape, num_classes):
    """
    Belirli aktivasyon fonksiyonlu test modeli oluşturur
    """
    model = models.Sequential([
        layers.Input(shape=input_shape),
        layers.Rescaling(1./255),
        layers.Flatten(),

        # Gizli katman - test edilecek aktivasyon
        layers.Dense(64, name="hidden_layer"),

        # Aktivasyon katmanını ayrı ekle (Leaky ReLU için)
        layers.LeakyReLU(alpha=0.1) if activation == 'leaky_relu'
        else layers.Activation(activation),

        # Çıkış katmanı
        layers.Dense(num_classes, activation='softmax', name="output")
    ], name=f"Model_{activation}")

    return model

# Test edilecek aktivasyon fonksiyonları
activations_to_test = {
    'relu': 'ReLU',
    'sigmoid': 'Sigmoid',
    'tanh': 'Tanh',
    'leaky_relu': 'Leaky ReLU'
}

print("🧪 AKTİVASYON FONKSİYONU KARŞILAŞTIRMASI")
print("=" * 60)
print("🎯 Test parametreleri:")
print(f"   📊 Model mimarisi: Flatten -> Dense(64) -> Dense({num_classes})")
print(f"   ⏰ Epoch sayısı: 3 (hızlı karşılaştırma)")
print(f"   🎲 Batch size: {BATCH_SIZE}")
print()

# Sonuçları saklamak için
activation_results = {}
activation_times = {}

print("🚀 Testler başlıyor...")
print("-" * 50)

total_start_time = time.time()

for i, (act_key, act_name) in enumerate(activations_to_test.items()):
    print(f"🔄 Test {i+1}/{len(activations_to_test)}: {act_name}")

    # Model oluştur
    test_model = create_activation_test_model(
        activation=act_key,
        input_shape=IMG_SIZE + (3,),
        num_classes=num_classes
    )

    # Modeli derle
    test_model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    # Eğitimi başlat
    start_time = time.time()

    history = test_model.fit(
        train_ds,
        epochs=3,  # Hızlı karşılaştırma için az epoch
        validation_data=val_ds,
        verbose=0  # Sessiz mod
    )

    end_time = time.time()

    # Sonuçları kaydet
    activation_results[act_name] = history.history
    activation_times[act_name] = end_time - start_time

    # Sonuçları yazdır
    final_val_acc = history.history['val_accuracy'][-1]
    training_time = end_time - start_time

    print(f"   ✅ {act_name}: Val Acc = %{final_val_acc*100:.2f}, Süre = {training_time:.1f}s")

    # Memory temizliği
    del test_model
    K.clear_session()

total_end_time = time.time()
total_time = total_end_time - total_start_time

print("-" * 50)
print(f"🏁 Toplam test süresi: {total_time:.2f} saniye")

# Karşılaştırma grafiğini oluştur
def plot_activation_comparison(results, times):
    """
    Aktivasyon fonksiyonu karşılaştırma grafikleri
    """
    fig = plt.figure(figsize=(18, 12))

    # 1. Validation Accuracy karşılaştırması
    ax1 = plt.subplot(2, 3, 1)
    for act_name, hist in results.items():
        epochs = range(1, len(hist['val_accuracy']) + 1)
        plt.plot(epochs, hist['val_accuracy'],
                label=act_name, marker='o', linewidth=2)

    plt.title('🎯 Doğrulama Doğruluğu Karşılaştırması', fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.ylim(0, 1)

    # 2. Training Loss karşılaştırması
    ax2 = plt.subplot(2, 3, 2)
    for act_name, hist in results.items():
        epochs = range(1, len(hist['loss']) + 1)
        plt.plot(epochs, hist['loss'],
                label=act_name, marker='s', linewidth=2)

    plt.title('📉 Eğitim Kaybı Karşılaştırması', fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True, alpha=0.3)

    # 3. Validation Loss karşılaştırması
    ax3 = plt.subplot(2, 3, 3)
    for act_name, hist in results.items():
        epochs = range(1, len(hist['val_loss']) + 1)
        plt.plot(epochs, hist['val_loss'],
                label=act_name, marker='^', linewidth=2)

    plt.title('📉 Doğrulama Kaybı Karşılaştırması', fontweight='bold')
    plt.xlabel('Epoch')
    plt.ylabel('Validation Loss')
    plt.legend()
    plt.grid(True, alpha=0.3)

    # 4. Final accuracy bar chart
    ax4 = plt.subplot(2, 3, 4)
    final_accuracies = [hist['val_accuracy'][-1] for hist in results.values()]
    colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4']

    bars = plt.bar(results.keys(), final_accuracies, color=colors, alpha=0.8)
    plt.title('📊 Final Doğrulama Doğruluğu', fontweight='bold')
    plt.ylabel('Accuracy')
    plt.ylim(0, 1)

    # Bar değerlerini göster
    for bar, acc in zip(bars, final_accuracies):
        height = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2., height + 0.01,
                f'{acc:.3f}', ha='center', va='bottom', fontweight='bold')

    plt.xticks(rotation=45)

    # 5. Training time karşılaştırması
    ax5 = plt.subplot(2, 3, 5)
    training_times = list(times.values())
    colors_time = ['#FF9999', '#66B2FF', '#99FF99', '#FFB366']

    bars_time = plt.bar(times.keys(), training_times, color=colors_time, alpha=0.8)
    plt.title('⏰ Eğitim Süresi Karşılaştırması', fontweight='bold')
    plt.ylabel('Süre (saniye)')

    # Bar değerlerini göster
    for bar, time_val in zip(bars_time, training_times):
        height = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2., height + 0.1,
                f'{time_val:.1f}s', ha='center', va='bottom', fontweight='bold')

    plt.xticks(rotation=45)

    # 6. Accuracy vs Time scatter plot
    ax6 = plt.subplot(2, 3, 6)
    scatter_colors = ['red', 'blue', 'green', 'orange']

    for i, (act_name, hist) in enumerate(results.items()):
        final_acc = hist['val_accuracy'][-1]
        time_taken = times[act_name]
        plt.scatter(time_taken, final_acc, s=200, alpha=0.7,
                   color=scatter_colors[i], label=act_name)
        plt.annotate(act_name, (time_taken, final_acc),
                    xytext=(5, 5), textcoords='offset points', fontsize=10)

    plt.title('⚡ Performans vs Hız', fontweight='bold')
    plt.xlabel('Eğitim Süresi (saniye)')
    plt.ylabel('Final Accuracy')
    plt.grid(True, alpha=0.3)
    plt.legend()

    plt.tight_layout()
    plt.suptitle('🧪 Aktivasyon Fonksiyonu Karşılaştırması',
                 fontsize=16, fontweight='bold', y=1.02)
    plt.show()

# Karşılaştırma grafiklerini çiz
plot_activation_comparison(activation_results, activation_times)

# En iyi performansı belirle ve özet çıkar
print("📈 AKTIVASYON FONKSIYONU KARŞILAŞTIRMA SONUÇLARI")
print("=" * 60)

best_accuracy = 0
best_activation = ""
fastest_activation = ""
fastest_time = float('inf')

for act_name, hist in activation_results.items():
    final_acc = hist['val_accuracy'][-1]
    time_taken = activation_times[act_name]

    print(f"🎯 {act_name}:")
    print(f"   📊 Final Accuracy: %{final_acc*100:.2f}")
    print(f"   ⏰ Eğitim Süresi: {time_taken:.2f} saniye")
    print(f"   📈 Accuracy Artışı: %{(final_acc - hist['val_accuracy'][0])*100:.2f}")
    print()

    if final_acc > best_accuracy:
        best_accuracy = final_acc
        best_activation = act_name

    if time_taken < fastest_time:
        fastest_time = time_taken
        fastest_activation = act_name

print("🏆 ÖZET:")
print(f"   🥇 En İyi Accuracy: {best_activation} (%{best_accuracy*100:.2f})")
print(f"   ⚡ En Hızlı: {fastest_activation} ({fastest_time:.2f}s)")

# Aktivasyon fonksiyonu önerileri
print("\n💡 AKTİVASYON FONKSİYONU REHBERİ:")
print("   🚀 ReLU: Genel amaçlı, hızlı, gradient problem yok")
print("   📊 Sigmoid: Binary sınıflandırma, gradient vanishing riski")
print("   🔄 Tanh: Sıfır merkezli, daha iyi gradient flow")
print("   🔧 Leaky ReLU: ReLU'nun gelişmiş versiyonu, dying neuron problemi yok")

"""# 📖 PART 4: Loss Fonksiyonları ve Optimizasyon
**Learning Rate**
Optimizasyoncunun hataları düzeltirken ne kadar büyük adımlar atacağını belirler. Çok büyük adım (yüksek oran) hedefi şaşırtır, çok küçük adım (düşük oran) ise eğitimi çok yavaşlatır.

📉 **Loss Fonksiyonları**
Loss (Kayıp) fonksiyonu, modelin tahminlerinin gerçek değerlerden ne kadar uzak olduğunu ölçer. Model bu kaybı minimize etmeye çalışır.
🎯 Ana Loss Fonksiyonları:

Sparse Categorical Crossentropy

* Çoklu sınıf problemleri için
* Etiketler integer format (0, 1, 2, ...)
Bizim projemizde kullanıyoruz


Categorical Crossentropy

* Çoklu sınıf problemleri için
* Etiketler one-hot encoded format


Binary Crossentropy

* İkili sınıflandırma için
* Çıkış 0 ile 1 arasında


Mean Squared Error (MSE)

* Regresyon problemleri için
* Sürekli değer tahmini

**Loss Fonksiyonu Seçimi: Neden Sparse Categorical Crossentropy?**
Loss Fonksiyonu, modelin **"yaptığı hata"**yı ölçer. Bu projede, modelimiz balığı 7 farklı türden birine sınıflandırmaya çalışıyor. Bu nedenle, kullanacağımız Loss Fonksiyonu, çok sınıflı (multiclass) sınıflandırma problemlerine uygun olmalıdır.

Burada "Sparse Categorical Crossentropy" (Seyrek Kategorik Çapraz Entropi) adında biraz karmaşık duran bir fonksiyon seçiyoruz. Bu seçimin ardında yatan iki basit neden var:

1. Çoklu Sınıflandırma (Categorical)
Balık türlerimiz (Black Sea Sprat, Bream vb.) birer kategoridir. Bu tür kategorileri doğru tahmin etmek için Crossentropy'yi kullanırız. Crossentropy, modelin tahmin ettiği olasılık dağılımı ile gerçek etiket arasındaki farkı ölçmekte en başarılı fonksiyondur.

2. Etiket Formatımız (Sparse)
Bizim veri setimizde, balık türleri etiketlenirken genellikle şu format kullanılır:

Gerçek Etiket: 0 (Black Sea Sprat)

Gerçek Etiket: 1 (Bream)

...

Gerçek Etiket: 6 (Shrimp)

Bu formatta, her bir balığın etiketine karşılık gelen sadece bir tane tamsayı (integer) vardır.

Eğer etiketlerimiz tamsayı yerine, her biri için ayrı bir sütun oluşturulmuş, [0, 0, 1, 0, 0, 0, 0] gibi bir one-hot encoded formatında olsaydı, "Categorical Crossentropy" kullanırdık.

Ancak bizim etiketlerimiz tamsayı olduğu için (daha seyrek bir temsil), Keras'ta Loss Fonksiyonu olarak Sparse Categorical Crossentropy'yi seçeriz.
"""

def create_loss_comparison_model(loss_function, input_shape, num_classes):
    """
    Belirli loss fonksiyonlu model oluşturur
    """
    model = models.Sequential([
        layers.Input(shape=input_shape),
        layers.Rescaling(1./255),
        layers.Flatten(),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.3),  # Overfitting önleme
        layers.Dense(num_classes, activation='softmax')
    ], name=f"LossTest_{loss_function}")

    return model

# Test edilecek loss fonksiyonları
loss_functions = {
    'sparse_categorical_crossentropy': 'Sparse Categorical CE',
    'categorical_crossentropy': 'Categorical CE',
    'mean_squared_error': 'Mean Squared Error'
}

print("📉 LOSS FONKSİYONU KARŞILAŞTIRMASI")
print("=" * 60)
print("⚠️  Not: Categorical CE ve MSE tam uyumlu olmayabilir (veri format farkı)")
print()

loss_results = {}
loss_training_times = {}

for i, (loss_key, loss_name) in enumerate(loss_functions.items()):
    print(f"🔄 Test {i+1}/{len(loss_functions)}: {loss_name}")

    try:
        # Model oluştur
        model = create_loss_comparison_model(
            loss_function=loss_key,
            input_shape=IMG_SIZE + (3,),
            num_classes=num_classes
        )

        # Özel compiler ayarları
        if loss_key == 'categorical_crossentropy':
            # One-hot encoding gerekli, skip bu test
            print(f"   ⚠️ {loss_name}: Veri format uyumsuzluğu nedeniyle atlando")
            continue
        elif loss_key == 'mean_squared_error':
            # MSE regresyon için tasarlandı, sınıflandırmada garip sonuçlar verebilir
            print(f"   ⚠️ {loss_name}: Sınıflandırma problemi için uygun değil, atlando")
            continue

        # Normal compile
        model.compile(
            optimizer='adam',
            loss=loss_key,
            metrics=['accuracy']
        )

        # Eğitim
        start_time = time.time()
        history = model.fit(
            train_ds,
            epochs=3,
            validation_data=val_ds,
            verbose=0
        )
        end_time = time.time()

        # Sonuçları kaydet
        loss_results[loss_name] = history.history
        loss_training_times[loss_name] = end_time - start_time

        final_val_acc = history.history['val_accuracy'][-1]
        print(f"   ✅ {loss_name}: Val Acc = %{final_val_acc*100:.2f}")

        # Memory temizliği
        del model
        K.clear_session()

    except Exception as e:
        print(f"   ❌ {loss_name}: Hata - {str(e)[:50]}...")

print(f"\n✅ Loss fonksiyonu testleri tamamlandı!")

# Sadece Sparse Categorical CE ile detaylı analiz
print("\n📊 SPARSE CATEGORICAL CROSSENTROPY ANALİZİ")
print("=" * 50)
print("Bu loss fonksiyonu neden balık sınıflandırması için ideal:")
print("   🎯 Çoklu sınıf problemleri için optimize edilmiş")
print("   📊 Integer etiketlerle çalışır (0, 1, 2, 3, ...)")
print("   ⚡ Hesaplama açısından verimli")
print("   🧠 Softmax aktivasyonuyla mükemmel uyum")

"""# 📖 PART 5: Optimizasyon Algoritmaları

Eğitim sırasında modelin ağırlıklarını güncellemek için **optimizer** kullanılır.  
Başlıca optimizasyon algoritmaları:  
- **SGD (Stochastic Gradient Descent)**: Klasik yöntem, yavaş ama sağlam.  
- **Adam:** En çok kullanılan, adaptif öğrenme oranı.  
- **RMSprop:** Özellikle RNN ve zaman serilerinde başarılı.  

Şimdi aynı modelde farklı optimizer’ları deneyelim ve karşılaştıralım.
"""

def create_optimizer_test_model(optimizer, input_shape, num_classes):
    """
    Belirli optimizer'lı model oluşturur
    """
    model = models.Sequential([
        layers.Input(shape=input_shape),
        layers.Rescaling(1./255),
        layers.Flatten(),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.2),
        layers.Dense(num_classes, activation='softmax')
    ], name=f"OptimizerTest")

    return model

# Test edilecek optimizer'lar
optimizers_to_test = {
    'sgd': ('SGD', tf.keras.optimizers.SGD(learning_rate=0.01)),
    'adam': ('Adam', tf.keras.optimizers.Adam(learning_rate=0.001)),
    'rmsprop': ('RMSprop', tf.keras.optimizers.RMSprop(learning_rate=0.001)),
    'adagrad': ('Adagrad', tf.keras.optimizers.Adagrad(learning_rate=0.01))
}

print("⚙️ OPTİMİZER KARŞILAŞTIRMASI")
print("=" * 60)

print("🎯 Test edilecek optimizer'lar:")
for opt_key, (opt_name, opt_obj) in optimizers_to_test.items():
    print(f"   📌 {opt_name}: {opt_obj.get_config()['learning_rate']} learning rate")
print()

optimizer_results = {}
optimizer_times = {}

for i, (opt_key, (opt_name, optimizer)) in enumerate(optimizers_to_test.items()):
    print(f"🔄 Test {i+1}/{len(optimizers_to_test)}: {opt_name}")

    # Model oluştur
    model = create_optimizer_test_model(
        optimizer=optimizer,
        input_shape=IMG_SIZE + (3,),
        num_classes=num_classes
    )

    # Modeli derle
    model.compile(
        optimizer=optimizer,
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    # Eğitim
    start_time = time.time()
    history = model.fit(
        train_ds,
        epochs=4,  # Optimizer farkını görmek için biraz daha fazla epoch
        validation_data=val_ds,
        verbose=0
    )
    end_time = time.time()

    # Sonuçları kaydet
    optimizer_results[opt_name] = history.history
    optimizer_times[opt_name] = end_time - start_time

    final_val_acc = history.history['val_accuracy'][-1]
    training_time = end_time - start_time
    print(f"   ✅ {opt_name}: Val Acc = %{final_val_acc*100:.2f}, Süre = {training_time:.1f}s")

    # Memory temizliği
    del model
    K.clear_session()

print("\n🏁 Optimizer testleri tamamlandı!")

# Optimizer karşılaştırma grafiği
def plot_optimizer_comparison(results, times):
    """
    Optimizer karşılaştırma grafikleri oluşturur
    """
    fig, axes = plt.subplots(2, 2, figsize=(16, 12))

    # 1. Validation Accuracy
    ax1 = axes[0, 0]
    for opt_name, hist in results.items():
        epochs = range(1, len(hist['val_accuracy']) + 1)
        ax1.plot(epochs, hist['val_accuracy'],
                label=opt_name, marker='o', linewidth=2)

    ax1.set_title('🎯 Doğrulama Doğruluğu', fontweight='bold')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Validation Accuracy')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    ax1.set_ylim(0, 1)

    # 2. Training Loss
    ax2 = axes[0, 1]
    for opt_name, hist in results.items():
        epochs = range(1, len(hist['loss']) + 1)
        ax2.plot(epochs, hist['loss'],
                label=opt_name, marker='s', linewidth=2)

    ax2.set_title('📉 Eğitim Kaybı', fontweight='bold')
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Training Loss')
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    # 3. Convergence Speed (Loss azalma hızı)
    ax3 = axes[1, 0]
    for opt_name, hist in results.items():
        loss_reduction = []
        initial_loss = hist['loss'][0]
        for loss in hist['loss']:
            reduction_percent = ((initial_loss - loss) / initial_loss) * 100
            loss_reduction.append(reduction_percent)

        epochs = range(1, len(loss_reduction) + 1)
        ax3.plot(epochs, loss_reduction,
                label=opt_name, marker='^', linewidth=2)

    ax3.set_title('⚡ Konverjans Hızı', fontweight='bold')
    ax3.set_xlabel('Epoch')
    ax3.set_ylabel('Loss Azalma Yüzdesi (%)')
    ax3.legend()
    ax3.grid(True, alpha=0.3)

    # 4. Final Performance vs Time
    ax4 = axes[1, 1]
    final_accuracies = [hist['val_accuracy'][-1] for hist in results.values()]
    training_times = list(times.values())
    colors = ['red', 'blue', 'green', 'orange']

    for i, (opt_name, acc, time_val) in enumerate(zip(results.keys(), final_accuracies, training_times)):
        ax4.scatter(time_val, acc, s=200, alpha=0.7,
                   color=colors[i], label=opt_name)
        ax4.annotate(opt_name, (time_val, acc),
                    xytext=(5, 5), textcoords='offset points')

    ax4.set_title('📊 Performans vs Süre', fontweight='bold')
    ax4.set_xlabel('Eğitim Süresi (saniye)')
    ax4.set_ylabel('Final Validation Accuracy')
    ax4.grid(True, alpha=0.3)
    ax4.legend()

    plt.tight_layout()
    plt.suptitle('⚙️ Optimizer Karşılaştırması', fontsize=16, fontweight='bold', y=1.02)
    plt.show()

# Optimizer karşılaştırma grafiklerini çiz
plot_optimizer_comparison(optimizer_results, optimizer_times)

# Optimizer analizi
print("📈 OPTİMİZER KARŞILAŞTIRMA ANALİZİ")
print("=" * 60)

best_optimizer = ""
best_performance = 0

for opt_name, hist in optimizer_results.items():
    final_acc = hist['val_accuracy'][-1]
    initial_loss = hist['loss'][0]
    final_loss = hist['loss'][-1]
    convergence_speed = ((initial_loss - final_loss) / initial_loss) * 100

    print(f"🎯 {opt_name}:")
    print(f"   📊 Final Accuracy: %{final_acc*100:.2f}")
    print(f"   📉 Loss Azalması: %{convergence_speed:.1f}")
    print(f"   ⏰ Eğitim Süresi: {optimizer_times[opt_name]:.2f}s")
    print(f"   💡 Stabilite: {'Kararlı' if max(hist['val_accuracy']) - min(hist['val_accuracy']) < 0.1 else 'Dalgalı'}")
    print()

    if final_acc > best_performance:
        best_performance = final_acc
        best_optimizer = opt_name

print("🏆 SONUÇ VE ÖNERİLER:")
print(f"   🥇 En İyi Optimizer: {best_optimizer} (%{best_performance*100:.2f})")
print()
print("💡 OPTIMIZER REHBERİ:")
print("   🚀 Adam: Genel amaçlı, adaptive learning rate, çoğu durumda iyi")
print("   📈 SGD: Klasik, basit, bazen daha kararlı sonuçlar")
print("   ⚡ RMSprop: RNN ve sequence modellerde etkili")
print("   📊 Adagrad: Sparse data için iyi, learning rate azalır")

"""# 📖 PART 5: Regularization Teknikleri (Aşırı Öğrenmeyi Önleme)
🛡️**Overfitting Nedir?**

Overfitting (Aşırı Öğrenme), modelin eğitim verilerini ezberleyip genel kuralları öğrenememesi durumudur.

🚨 Overfitting Belirtileri: Modelin sadece eğitim verilerini ezberlemesi, ancak yeni (görmediği) balık görsellerini tanımakta zorlanması." En iyi benzetme: "Sınav sorularını ezberleyen ama konuyu anlamayan öğrenci.

* Eğitim accuracy yüksek, validation accuracy düşük
* Validation loss artmaya başlıyor
* Model yeni verilerle başarısız

🛡️ Regularization Teknikleri:

* Dropout: Rastgele nöronları eğitim sırasında kapatır(Eğitim sırasında nöronların rastgele bir kısmını 'uyutarak' modelin tek bir nörona aşırı bağımlı olmasını engeller. Bu, takım çalışmasına zorlamak gibidir.)
* Batch Normalization: Katman girişlerini normalize eder
* L1/L2 Regularization: Ağırlıkları cezalandırır
* Early Stopping: Validation loss artmaya başlayınca durdurur
"""

def create_regularization_model(reg_type, input_shape, num_classes):
    """
    Farklı regularization teknikleriyle model oluşturur
    """
    models_dict = {
        'baseline': models.Sequential([
            layers.Input(shape=input_shape),
            layers.Rescaling(1./255),
            layers.Flatten(),
            layers.Dense(256, activation='relu'),
            layers.Dense(128, activation='relu'),
            layers.Dense(num_classes, activation='softmax')
        ], name="Baseline"),

        'dropout': models.Sequential([
            layers.Input(shape=input_shape),
            layers.Rescaling(1./255),
            layers.Flatten(),
            layers.Dense(256, activation='relu'),
            layers.Dropout(0.5),  # %50 nöron kapatılır
            layers.Dense(128, activation='relu'),
            layers.Dropout(0.3),  # %30 nöron kapatılır
            layers.Dense(num_classes, activation='softmax')
        ], name="Dropout"),

        'batch_norm': models.Sequential([
            layers.Input(shape=input_shape),
            layers.Rescaling(1./255),
            layers.Flatten(),
            layers.Dense(256, activation='relu'),
            layers.BatchNormalization(),  # Normalizasyon
            layers.Dense(128, activation='relu'),
            layers.BatchNormalization(),
            layers.Dense(num_classes, activation='softmax')
        ], name="BatchNormalization"),

        'l2_reg': models.Sequential([
            layers.Input(shape=input_shape),
            layers.Rescaling(1./255),
            layers.Flatten(),
            layers.Dense(256, activation='relu',
                        kernel_regularizer=tf.keras.regularizers.l2(0.01)),  # L2 ceza
            layers.Dense(128, activation='relu',
                        kernel_regularizer=tf.keras.regularizers.l2(0.01)),
            layers.Dense(num_classes, activation='softmax')
        ], name="L2Regularization"),

        'combined': models.Sequential([
            layers.Input(shape=input_shape),
            layers.Rescaling(1./255),
            layers.Flatten(),
            layers.Dense(256, activation='relu',
                        kernel_regularizer=tf.keras.regularizers.l2(0.005)),
            layers.Dropout(0.4),
            layers.BatchNormalization(),
            layers.Dense(128, activation='relu',
                        kernel_regularizer=tf.keras.regularizers.l2(0.005)),
            layers.Dropout(0.2),
            layers.Dense(num_classes, activation='softmax')
        ], name="Combined")
    }

    return models_dict[reg_type]

print("🛡️ REGULARİZATİON TEKNİKLERİ KARŞILAŞTIRMASI")
print("=" * 60)

regularization_techniques = {
    'baseline': 'Temel Model (Regularization Yok)',
    'dropout': 'Dropout',
    'batch_norm': 'Batch Normalization',
    'l2_reg': 'L2 Regularization',
    'combined': 'Kombine (Dropout + BatchNorm + L2)'
}

reg_results = {}
reg_times = {}

print("🎯 Test edilecek teknikler:")
for reg_key, reg_name in regularization_techniques.items():
    print(f"   📌 {reg_name}")
print()

for i, (reg_key, reg_name) in enumerate(regularization_techniques.items()):
    print(f"🔄 Test {i+1}/{len(regularization_techniques)}: {reg_name}")

    # Model oluştur
    model = create_regularization_model(
        reg_type=reg_key,
        input_shape=IMG_SIZE + (3,),
        num_classes=num_classes
    )

    # Modeli derle
    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    # Eğitim (daha fazla epoch - overfitting'i gözlemlemek için)
    start_time = time.time()
    history = model.fit(
        train_ds,
        epochs=6,  # Overfitting gözlemlemek için daha fazla epoch
        validation_data=val_ds,
        verbose=0
    )
    end_time = time.time()

    # Sonuçları kaydet
    reg_results[reg_name] = history.history
    reg_times[reg_name] = end_time - start_time

    # Overfitting analizi
    final_train_acc = history.history['accuracy'][-1]
    final_val_acc = history.history['val_accuracy'][-1]
    overfitting_gap = final_train_acc - final_val_acc

    print(f"   📊 Train Acc: %{final_train_acc*100:.2f}")
    print(f"   🎯 Val Acc: %{final_val_acc*100:.2f}")
    print(f"   📉 Overfitting Gap: %{overfitting_gap*100:.2f}")

    if overfitting_gap > 0.15:
        print(f"   🚨 Yüksek overfitting riski!")
    elif overfitting_gap > 0.05:
        print(f"   ⚠️ Hafif overfitting")
    else:
        print(f"   ✅ Dengeli model")
    print()

    # Memory temizliği
    del model
    K.clear_session()

print("🏁 Regularization testleri tamamlandı!")

# Regularization karşılaştırma grafiği
def plot_regularization_comparison(results):
    """
    Regularization tekniklerini karşılaştıran detaylı grafikler
    """
    fig, axes = plt.subplots(3, 2, figsize=(16, 18))

    # 1. Training vs Validation Accuracy
    ax1 = axes[0, 0]
    for reg_name, hist in results.items():
        epochs = range(1, len(hist['accuracy']) + 1)
        ax1.plot(epochs, hist['accuracy'], '--', alpha=0.7, label=f'{reg_name} (Train)')
        ax1.plot(epochs, hist['val_accuracy'], '-', linewidth=2, label=f'{reg_name} (Val)')

    ax1.set_title('🎯 Eğitim vs Doğrulama Doğruluğu', fontweight='bold')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Accuracy')
    ax1.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    ax1.grid(True, alpha=0.3)

    # 2. Overfitting Gap Analysis
    ax2 = axes[0, 1]
    overfitting_gaps = []
    reg_names = []

    for reg_name, hist in results.items():
        final_train = hist['accuracy'][-1]
        final_val = hist['val_accuracy'][-1]
        gap = final_train - final_val
        overfitting_gaps.append(gap)
        reg_names.append(reg_name.replace(' (', '\n('))  # İsim kırma

    colors = ['red' if gap > 0.15 else 'orange' if gap > 0.05 else 'green'
              for gap in overfitting_gaps]

    bars = ax2.bar(range(len(reg_names)), overfitting_gaps, color=colors, alpha=0.7)
    ax2.set_title('📉 Overfitting Analizi (Train - Val Acc)', fontweight='bold')
    ax2.set_ylabel('Accuracy Farkı')
    ax2.set_xticks(range(len(reg_names)))
    ax2.set_xticklabels(reg_names, rotation=45, ha='right')
    ax2.axhline(y=0.05, color='orange', linestyle='--', alpha=0.7, label='Hafif Overfitting')
    ax2.axhline(y=0.15, color='red', linestyle='--', alpha=0.7, label='Yüksek Overfitting')
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    # Bar değerlerini göster
    for bar, gap in zip(bars, overfitting_gaps):
        height = bar.get_height()
        ax2.text(bar.get_x() + bar.get_width()/2., height + 0.005,
                f'{gap:.3f}', ha='center', va='bottom', fontweight='bold')

    # 3. Loss Comparison
    ax3 = axes[1, 0]
    for reg_name, hist in results.items():
        epochs = range(1, len(hist['loss']) + 1)
        ax3.plot(epochs, hist['loss'], '--', alpha=0.7)
        ax3.plot(epochs, hist['val_loss'], '-', linewidth=2, label=reg_name)

    ax3.set_title('📉 Kayıp Fonksiyonu Karşılaştırması', fontweight='bold')
    ax3.set_xlabel('Epoch')
    ax3.set_ylabel('Loss')
    ax3.legend()
    ax3.grid(True, alpha=0.3)

    # 4. Final Performance Bar Chart
    ax4 = axes[1, 1]
    final_val_accs = [hist['val_accuracy'][-1] for hist in results.values()]
    colors_perf = plt.cm.viridis(np.linspace(0, 1, len(final_val_accs)))

    bars_perf = ax4.bar(range(len(reg_names)), final_val_accs, color=colors_perf, alpha=0.8)
    ax4.set_title('📊 Final Doğrulama Performansı', fontweight='bold')
    ax4.set_ylabel('Validation Accuracy')
    ax4.set_xticks(range(len(reg_names)))
    ax4.set_xticklabels(reg_names, rotation=45, ha='right')
    ax4.set_ylim(0, 1)

    # Bar değerlerini göster
    for bar, acc in zip(bars_perf, final_val_accs):
        height = bar.get_height()
        ax4.text(bar.get_x() + bar.get_width()/2., height + 0.01,
                f'{acc:.3f}', ha='center', va='bottom', fontweight='bold')
    ax4.grid(True, alpha=0.3)

    # 5. Training Stability (Validation accuracy variance)
    ax5 = axes[2, 0]
    stability_scores = []
    for reg_name, hist in results.items():
        val_acc_variance = np.var(hist['val_accuracy'])
        stability_scores.append(val_acc_variance)

    colors_stab = ['green' if score < 0.001 else 'orange' if score < 0.005 else 'red'
                   for score in stability_scores]

    bars_stab = ax5.bar(range(len(reg_names)), stability_scores, color=colors_stab, alpha=0.7)
    ax5.set_title('📈 Eğitim Kararlılığı (Val Acc Varyansı)', fontweight='bold')
    ax5.set_ylabel('Varyans')
    ax5.set_xticks(range(len(reg_names)))
    ax5.set_xticklabels(reg_names, rotation=45, ha='right')

    # Bar değerlerini göster
    for bar, score in zip(bars_stab, stability_scores):
        height = bar.get_height()
        ax5.text(bar.get_x() + bar.get_width()/2., height + height*0.05,
                f'{score:.4f}', ha='center', va='bottom', fontweight='bold', fontsize=9)
    ax5.grid(True, alpha=0.3)

    # 6. Learning Curves Comparison (last 3 epochs trend)
    ax6 = axes[2, 1]
    improvement_rates = []
    for reg_name, hist in results.items():
        # Son 3 epoch'taki val_accuracy artış oranı
        recent_accs = hist['val_accuracy'][-3:]
        if len(recent_accs) >= 2:
            improvement = (recent_accs[-1] - recent_accs[0]) / len(recent_accs)
        else:
            improvement = 0
        improvement_rates.append(improvement)

    colors_imp = ['green' if rate > 0.01 else 'orange' if rate > -0.01 else 'red'
                  for rate in improvement_rates]

    bars_imp = ax6.bar(range(len(reg_names)), improvement_rates, color=colors_imp, alpha=0.7)
    ax6.set_title('📈 Son Dönem İyileştirme Trendi', fontweight='bold')
    ax6.set_ylabel('Accuracy Artış Oranı')
    ax6.set_xticks(range(len(reg_names)))
    ax6.set_xticklabels(reg_names, rotation=45, ha='right')
    ax6.axhline(y=0, color='black', linestyle='-', alpha=0.3)

    # Bar değerlerini göster
    for bar, rate in zip(bars_imp, improvement_rates):
        height = bar.get_height()
        y_pos = height + 0.002 if height >= 0 else height - 0.002
        ax6.text(bar.get_x() + bar.get_width()/2., y_pos,
                f'{rate:.3f}', ha='center', va='bottom' if height >= 0 else 'top',
                fontweight='bold', fontsize=9)
    ax6.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.suptitle('🛡️ Regularization Teknikleri Karşılaştırması',
                 fontsize=16, fontweight='bold', y=0.98)
    plt.show()

# Regularization karşılaştırma grafiklerini çiz
plot_regularization_comparison(reg_results)

# Detaylı regularization analizi
print("📊 REGULARİZATİON TEKNİK ANALİZİ")
print("=" * 60)

best_reg_technique = ""
best_reg_score = 0
most_stable = ""
lowest_variance = float('inf')

for reg_name, hist in reg_results.items():
    # Performans metrikleri
    final_train_acc = hist['accuracy'][-1]
    final_val_acc = hist['val_accuracy'][-1]
    overfitting_gap = final_train_acc - final_val_acc

    # Kararlılık metrikleri
    val_acc_variance = np.var(hist['val_accuracy'])
    val_acc_std = np.std(hist['val_accuracy'])

    # İyileştirme trendi
    recent_val_accs = hist['val_accuracy'][-3:]
    improvement_trend = (recent_val_accs[-1] - recent_val_accs[0]) / len(recent_val_accs) if len(recent_val_accs) >= 2 else 0

    print(f"🎯 {reg_name}:")
    print(f"   📊 Final Val Accuracy: %{final_val_acc*100:.2f}")
    print(f"   📉 Overfitting Gap: %{overfitting_gap*100:.2f}")
    print(f"   📈 Kararlılık (Std Dev): {val_acc_std:.4f}")
    print(f"   🔄 Son Dönem Trend: {improvement_trend:+.4f}")

    # Overfitting durumu
    if overfitting_gap > 0.15:
        print(f"   🚨 Durum: YÜKSEK OVERFİTTİNG")
    elif overfitting_gap > 0.05:
        print(f"   ⚠️ Durum: HAFİF OVERFİTTİNG")
    else:
        print(f"   ✅ Durum: DENGELİ MODEL")

    # Genel değerlendirme skoru (performans + kararlılık)
    balance_score = final_val_acc - (overfitting_gap * 0.5) - (val_acc_variance * 10)
    print(f"   🏆 Denge Skoru: {balance_score:.3f}")
    print()

    # En iyi tekniği belirle
    if balance_score > best_reg_score:
        best_reg_score = balance_score
        best_reg_technique = reg_name

    # En kararlı tekniği belirle
    if val_acc_variance < lowest_variance:
        lowest_variance = val_acc_variance
        most_stable = reg_name

print("🏆 REGULARIZATION SONUÇLARI:")
print(f"   🥇 En Dengeli Teknik: {best_reg_technique} (Skor: {best_reg_score:.3f})")
print(f"   ⚖️ En Kararlı Teknik: {most_stable} (Varyans: {lowest_variance:.4f})")
print()

print("💡 REGULARİZATİON REHBERİ:")
print("   🎯 Dropout: Basit ve etkili, %20-50 arasında kullan")
print("   📊 Batch Norm: Eğitimi hızlandırır, gradient flow'u iyileştirir")
print("   ⚖️ L2 Reg: Ağırlıkları küçük tutar, 0.001-0.01 arası dene")
print("   🔄 Early Stopping: En güvenli yöntem, validation loss'u izle")
print("   🛡️ Kombine: Birden fazla tekniği birleştir, daha güçlü koruma")

"""# 📖 PART 7: CNN Katmanları (Conv2D ve Pooling)

🖼️ Convolutional Neural Networks (CNN)
CNN, görüntü işleme için özel olarak tasarlanmış neural network türüdür. İnsan görsel korteksinden ilham alır. Her bir filtre (kernel), bir büyüteç gibidir. Görseldeki kenarları, köşeleri veya balığın pulları gibi küçük desenleri arar. Bu sayede model, görsellerin özelliklerini otomatik olarak öğrenir.

🧠 **CNN'in Avantajları:**

Uzamsal yapıyı korur (piksel komşulukları)
Az parametre (ağırlık paylaşımı)
Translation invariant (nesne konumu fark etmez)
Hierarchical feature learning (kenar → doku → şekil → nesne)

🔍 **CNN Katman Türleri**:

* Conv2D (Konvolüsyon)

Görüntü üzerinde filtreler (kernels) gezdirir
Kenar, köşe, doku gibi özellikleri çıkarır
Parametre: filter sayısı, kernel boyutu, stride, padding


* MaxPooling2D

Özellik haritasının boyutunu küçültür
En büyük değeri seçer (down-sampling)
Hesaplama yükünü azaltır, invariance sağlar


* AveragePooling2D

Ortalama değeri alır
MaxPooling'e alternatif
"""

def create_cnn_model(cnn_type, input_shape, num_classes):
    """
    Farklı CNN mimarileri oluşturur
    """
    models_dict = {
        'simple_cnn': models.Sequential([
            layers.Input(shape=input_shape),
            layers.Rescaling(1./255),

            # İlk konvolüsyon bloğu
            layers.Conv2D(32, (3, 3), activation='relu', name='conv1'),
            layers.MaxPooling2D((2, 2), name='pool1'),

            # İkinci konvolüsyon bloğu
            layers.Conv2D(64, (3, 3), activation='relu', name='conv2'),
            layers.MaxPooling2D((2, 2), name='pool2'),

            # Sınıflandırma katmanları
            layers.Flatten(),
            layers.Dense(64, activation='relu', name='fc1'),
            layers.Dense(num_classes, activation='softmax', name='output')
        ], name="SimpleCNN"),

        'deep_cnn': models.Sequential([
            layers.Input(shape=input_shape),
            layers.Rescaling(1./255),

            # Birinci blok
            layers.Conv2D(32, (3, 3), activation='relu'),
            layers.Conv2D(32, (3, 3), activation='relu'),
            layers.MaxPooling2D((2, 2)),
            layers.Dropout(0.25),

            # İkinci blok
            layers.Conv2D(64, (3, 3), activation='relu'),
            layers.Conv2D(64, (3, 3), activation='relu'),
            layers.MaxPooling2D((2, 2)),
            layers.Dropout(0.25),

            # Üçüncü blok
            layers.Conv2D(128, (3, 3), activation='relu'),
            layers.MaxPooling2D((2, 2)),
            layers.Dropout(0.25),

            # Sınıflandırma
            layers.Flatten(),
            layers.Dense(128, activation='relu'),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation='softmax')
        ], name="DeepCNN"),

        'vgg_style': models.Sequential([
            layers.Input(shape=input_shape),
            layers.Rescaling(1./255),

            # VGG-style bloklar
            # Blok 1
            layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
            layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
            layers.MaxPooling2D((2, 2)),

            # Blok 2
            layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
            layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
            layers.MaxPooling2D((2, 2)),

            # Blok 3
            layers.Conv2D(256, (3, 3), activation='relu', padding='same'),
            layers.MaxPooling2D((2, 2)),

            # Classifier
            layers.Flatten(),
            layers.Dense(256, activation='relu'),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation='softmax')
        ], name="VGGStyle"),

        'residual_cnn': models.Sequential([
            layers.Input(shape=input_shape),
            layers.Rescaling(1./255),

            # İlk konvolüsyon
            layers.Conv2D(64, (7, 7), strides=2, padding='same', activation='relu'),
            layers.MaxPooling2D((3, 3), strides=2, padding='same'),

            # Residual benzeri bloklar (basitleştirilmiş)
            layers.Conv2D(64, (3, 3), padding='same', activation='relu'),
            layers.Conv2D(64, (3, 3), padding='same', activation='relu'),
            layers.MaxPooling2D((2, 2)),

            layers.Conv2D(128, (3, 3), padding='same', activation='relu'),
            layers.Conv2D(128, (3, 3), padding='same', activation='relu'),
            layers.MaxPooling2D((2, 2)),

            # Global average pooling (FC yerine)
            layers.GlobalAveragePooling2D(),
            layers.Dense(num_classes, activation='softmax')
        ], name="ResidualCNN")
    }

    return models_dict[cnn_type]

print("🖼️ CNN MİMARİLERİ KARŞILAŞTIRMASI")
print("=" * 60)

cnn_architectures = {
    'simple_cnn': 'Basit CNN (2 Conv Blok)',
    'deep_cnn': 'Derin CNN (3 Conv Blok + Dropout)',
    'vgg_style': 'VGG Tarzı (Çift Conv + Padding)',
    'residual_cnn': 'Residual CNN (Global Pooling)'
}

print("🏗️ Test edilecek CNN mimarileri:")
for cnn_key, cnn_name in cnn_architectures.items():
    print(f"   📌 {cnn_name}")
print()

cnn_results = {}
cnn_times = {}
cnn_params = {}

for i, (cnn_key, cnn_name) in enumerate(cnn_architectures.items()):
    print(f"🔄 Test {i+1}/{len(cnn_architectures)}: {cnn_name}")

    # Model oluştur
    model = create_cnn_model(
        cnn_type=cnn_key,
        input_shape=IMG_SIZE + (3,),
        num_classes=num_classes
    )

    # Model bilgilerini kaydet
    total_params = model.count_params()
    cnn_params[cnn_name] = total_params
    print(f"   📊 Toplam parametre sayısı: {total_params:,}")

    # Modeli derle
    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    # Eğitim
    start_time = time.time()
    history = model.fit(
        train_ds,
        epochs=5,  # CNN'ler daha yavaş, az epoch
        validation_data=val_ds,
        verbose=0
    )
    end_time = time.time()

    # Sonuçları kaydet
    cnn_results[cnn_name] = history.history
    cnn_times[cnn_name] = end_time - start_time

    final_val_acc = history.history['val_accuracy'][-1]
    training_time = end_time - start_time

    print(f"   ✅ Val Accuracy: %{final_val_acc*100:.2f}")
    print(f"   ⏰ Eğitim süresi: {training_time:.1f} saniye")
    print(f"   ⚡ Saniye/Epoch: {training_time/5:.1f}s")
    print()

    # Memory temizliği
    del model
    K.clear_session()

print("🏁 CNN mimarisi testleri tamamlandı!")

# CNN karşılaştırma grafiği
def plot_cnn_comparison(results, times, params):
    """
    CNN mimarilerini karşılaştıran kapsamlı grafikler
    """
    fig, axes = plt.subplots(3, 2, figsize=(16, 18))

    # 1. Validation Accuracy Progression
    ax1 = axes[0, 0]
    for cnn_name, hist in results.items():
        epochs = range(1, len(hist['val_accuracy']) + 1)
        ax1.plot(epochs, hist['val_accuracy'],
                label=cnn_name, marker='o', linewidth=2)

    ax1.set_title('🎯 Doğrulama Doğruluğu Gelişimi', fontweight='bold')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Validation Accuracy')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    ax1.set_ylim(0, 1)

    # 2. Training vs Validation Loss
    ax2 = axes[0, 1]
    for cnn_name, hist in results.items():
        epochs = range(1, len(hist['loss']) + 1)
        ax2.plot(epochs, hist['loss'], '--', alpha=0.7, label=f'{cnn_name} (Train)')
        ax2.plot(epochs, hist['val_loss'], '-', linewidth=2, label=f'{cnn_name} (Val)')

    ax2.set_title('📉 Eğitim vs Doğrulama Kaybı', fontweight='bold')
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Loss')
    ax2.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    ax2.grid(True, alpha=0.3)

    # 3. Parameter Count vs Performance
    ax3 = axes[1, 0]
    final_accuracies = [hist['val_accuracy'][-1] for hist in results.values()]
    param_counts = list(params.values())
    colors = ['red', 'blue', 'green', 'orange']

    for i, (name, acc, param_count) in enumerate(zip(results.keys(), final_accuracies, param_counts)):
        ax3.scatter(param_count, acc, s=200, alpha=0.7,
                   color=colors[i], label=name)
        ax3.annotate(name.replace(' (', '\n('), (param_count, acc),
                    xytext=(5, 5), textcoords='offset points', fontsize=9)

    ax3.set_title('📊 Parametre Sayısı vs Performans', fontweight='bold')
    ax3.set_xlabel('Toplam Parametre Sayısı')
    ax3.set_ylabel('Final Validation Accuracy')
    ax3.grid(True, alpha=0.3)
    ax3.legend()

    # 4. Training Time vs Performance
    ax4 = axes[1, 1]
    training_times = list(times.values())

    for i, (name, acc, time_val) in enumerate(zip(results.keys(), final_accuracies, training_times)):
        ax4.scatter(time_val, acc, s=200, alpha=0.7,
                   color=colors[i], label=name)
        ax4.annotate(name.replace(' (', '\n('), (time_val, acc),
                    xytext=(5, 5), textcoords='offset points', fontsize=9)

    ax4.set_title('⏰ Eğitim Süresi vs Performans', fontweight='bold')
    ax4.set_xlabel('Eğitim Süresi (saniye)')
    ax4.set_ylabel('Final Validation Accuracy')
    ax4.grid(True, alpha=0.3)
    ax4.legend()

    # 5. Architecture Efficiency (Accuracy per Parameter)
    ax5 = axes[2, 0]
    efficiency_scores = [acc / (param_count / 1000) for acc, param_count in zip(final_accuracies, param_counts)]
    colors_eff = plt.cm.viridis(np.linspace(0, 1, len(efficiency_scores)))

    bars = ax5.bar(range(len(results)), efficiency_scores, color=colors_eff, alpha=0.8)
    ax5.set_title('⚡ Mimari Verimlilik (Acc/1K Param)', fontweight='bold')
    ax5.set_ylabel('Verimlilik Skoru')
    ax5.set_xticks(range(len(results)))
    ax5.set_xticklabels([name.replace(' (', '\n(') for name in results.keys()], rotation=45, ha='right')

    # Bar değerlerini göster
    for bar, score in zip(bars, efficiency_scores):
        height = bar.get_height()
        ax5.text(bar.get_x() + bar.get_width()/2., height + height*0.05,
                f'{score:.3f}', ha='center', va='bottom', fontweight='bold', fontsize=10)
    ax5.grid(True, alpha=0.3)

    # 6. Learning Speed Analysis (First epoch improvement)
    ax6 = axes[2, 1]
    learning_speeds = []
    for cnn_name, hist in results.items():
        if len(hist['val_accuracy']) >= 2:
            first_epoch_improvement = hist['val_accuracy'][1] - hist['val_accuracy'][0]
        else:
            first_epoch_improvement = 0
        learning_speeds.append(first_epoch_improvement)

    colors_speed = ['green' if speed > 0.1 else 'orange' if speed > 0.05 else 'red'
                    for speed in learning_speeds]

    bars_speed = ax6.bar(range(len(results)), learning_speeds, color=colors_speed, alpha=0.7)
    ax6.set_title('🚀 Öğrenme Hızı (1. Epoch İyileştirme)', fontweight='bold')
    ax6.set_ylabel('Accuracy Artışı')
    ax6.set_xticks(range(len(results)))
    ax6.set_xticklabels([name.replace(' (', '\n(') for name in results.keys()], rotation=45, ha='right')

    # Bar değerlerini göster
    for bar, speed in zip(bars_speed, learning_speeds):
        height = bar.get_height()
        y_pos = height + 0.005 if height >= 0 else height - 0.005
        ax6.text(bar.get_x() + bar.get_width()/2., y_pos,
                f'{speed:.3f}', ha='center', va='bottom' if height >= 0 else 'top',
                fontweight='bold', fontsize=10)
    ax6.axhline(y=0, color='black', linestyle='-', alpha=0.3)
    ax6.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.suptitle('🖼️ CNN Mimarilerinin Karşılaştırması',
                 fontsize=16, fontweight='bold', y=0.98)
    plt.show()

# CNN karşılaştırma grafiklerini çiz
plot_cnn_comparison(cnn_results, cnn_times, cnn_params)

# Detaylı CNN analizi
print("📊 CNN MİMARİ ANALİZİ")
print("=" * 60)

best_cnn = ""
best_cnn_performance = 0
most_efficient = ""
best_efficiency = 0

for cnn_name, hist in cnn_results.items():
    final_val_acc = hist['val_accuracy'][-1]
    param_count = cnn_params[cnn_name]
    training_time = cnn_times[cnn_name]

    # Verimlilik hesaplama
    efficiency = final_val_acc / (param_count / 1000)  # Accuracy per 1K parameters
    time_efficiency = final_val_acc / (training_time / 60)  # Accuracy per minute

    # Learning speed
    learning_speed = hist['val_accuracy'][1] - hist['val_accuracy'][0] if len(hist['val_accuracy']) >= 2 else 0

    print(f"🖼️ {cnn_name}:")
    print(f"   📊 Final Val Accuracy: %{final_val_acc*100:.2f}")
    print(f"   🧮 Toplam parametre: {param_count:,}")
    print(f"   ⏰ Eğitim süresi: {training_time:.1f} saniye")
    print(f"   ⚡ Parametre verimliliği: {efficiency:.3f}")
    print(f"   🚀 Zaman verimliliği: {time_efficiency:.3f}")
    print(f"   📈 İlk epoch öğrenme: %{learning_speed*100:.2f}")

    # Memory usage estimation (rough)
    estimated_memory_mb = param_count * 4 / (1024 * 1024)  # 4 bytes per param
    print(f"   💾 Tahmini memory: {estimated_memory_mb:.1f} MB")
    print()

    if final_val_acc > best_cnn_performance:
        best_cnn_performance = final_val_acc
        best_cnn = cnn_name

    if efficiency > best_efficiency:
        best_efficiency = efficiency
        most_efficient = cnn_name

print("🏆 CNN MİMARİ SONUÇLARI:")
print(f"   🥇 En İyi Performans: {best_cnn} (%{best_cnn_performance*100:.2f})")
print(f"   ⚡ En Verimli Mimari: {most_efficient} ({best_efficiency:.3f})")
print()

print("💡 CNN MİMARİ REHBERİ:")
print("   🏗️ Basit CNN: Az veri için, hızlı prototype")
print("   🏢 Derin CNN: Daha karmaşık özellikler, dropout ile overfitting kontrolü")
print("   🏛️ VGG Tarzı: Klasik mimari, güvenilir sonuçlar")
print("   🔄 Residual: Çok derin ağlar için, gradient flow problemi çözümü")
print("   📏 Global Pooling: FC katmanların yerine, daha az parametre")

"""# 📖 PART 7: Transfer Learning (Önceden Eğitilmiş Modeller)
🚀 Transfer Learning Nedir?
Transfer Learning, önceden büyük veri setlerinde (ImageNet gibi) eğitilmiş modellerin bilgisini yeni görevlerde kullanma tekniğidir.
Başka bir problemde (örneğin binlerce genel görseli tanımada) eğitilmiş bir 'uzman' modeli alıp, sadece son birkaç katmanını bizim balık problemimize göre ayarlıyoruz. Bu, sıfırdan eğitimden çok daha hızlı ve etkilidir.

🎯 Avantajları:

- Hızlı eğitim (birkaç epoch)
- Az veri ile yüksek performans
- Daha iyi özellik çıkarma
- Hesaplama maliyeti düşük

🔄 Transfer Learning Stratejileri:

* Feature Extraction: Base model dondurulur, sadece classifier eğitilir. Uzmanın (önceden eğitilmiş model) temel görsel tanıma bilgisini koruma altına alıyoruz ki, küçük balık veri setimizle bu büyük bilgiyi yanlışlıkla bozmayalım.

* Fine-Tuning: Base model'in son katmanları da eğitime dahil edilir

* Full Training: Tüm model yeniden eğitilir (çok veri gerekir)
"""

def create_transfer_model(base_model_name, input_shape, num_classes, strategy='feature_extraction'):
    """
    Transfer learning modelleri oluşturur
    """
    # Base model seçimi
    if base_model_name == 'mobilenetv2':
        base_model = tf.keras.applications.MobileNetV2(
            input_shape=input_shape,
            include_top=False,  # Son sınıflandırma katmanını dahil etme
            weights='imagenet'  # ImageNet ağırlıklarını kullan
        )
        preprocess_func = tf.keras.applications.mobilenet_v2.preprocess_input
    elif base_model_name == 'vgg16':
        base_model = tf.keras.applications.VGG16(
            input_shape=input_shape,
            include_top=False,
            weights='imagenet'
        )
        preprocess_func = tf.keras.applications.vgg16.preprocess_input
    elif base_model_name == 'resnet50':
        base_model = tf.keras.applications.ResNet50(
            input_shape=input_shape,
            include_top=False,
            weights='imagenet'
        )
        preprocess_func = tf.keras.applications.resnet50.preprocess_input
    elif base_model_name == 'efficientnetb0':
        base_model = tf.keras.applications.EfficientNetB0(
            input_shape=input_shape,
            include_top=False,
            weights='imagenet'
        )
        preprocess_func = tf.keras.applications.efficientnet.preprocess_input

    # Strategy'ye göre base model ayarları
    if strategy == 'feature_extraction':
        base_model.trainable = False  # Base model'i dondur
    elif strategy == 'fine_tuning':
        base_model.trainable = True   # Base model'i eğitilebilir yap
        # Son birkaç katmanı eğit, diğerlerini dondur
        for layer in base_model.layers[:-20]:  # Son 20 katman hariç dondur
            layer.trainable = False
    elif strategy == 'full_training':
        base_model.trainable = True   # Tüm katmanları eğit

    # Model mimarisi oluştur
    model = models.Sequential([
        layers.Input(shape=input_shape),

        # Veri augmentation (opsiyonel)
        layers.RandomFlip("horizontal"),
        layers.RandomRotation(0.1),
        layers.RandomZoom(0.1),

        # Preprocessing - Lambda layer ile fonksiyonu sarmalayın
        layers.Lambda(lambda x: preprocess_func(x)),

        # Base model
        base_model,

        # Custom classifier head
        layers.GlobalAveragePooling2D(),
        layers.Dropout(0.3),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.2),
        layers.Dense(num_classes, activation='softmax')

    ], name=f"Transfer_{base_model_name}_{strategy}")

    return model

print("🚀 TRANSFER LEARNING KARŞILAŞTIRMASI")
print("=" * 60)

# Test edilecek modeller ve stratejiler
transfer_configs = {
    'mobilenetv2_feature': ('mobilenetv2', 'feature_extraction', 'MobileNetV2 (Feature Extraction)'),
    'mobilenetv2_finetune': ('mobilenetv2', 'fine_tuning', 'MobileNetV2 (Fine-Tuning)'),
    'vgg16_feature': ('vgg16', 'feature_extraction', 'VGG16 (Feature Extraction)'),
    'resnet50_feature': ('resnet50', 'feature_extraction', 'ResNet50 (Feature Extraction)')
}

print("🎯 Test edilecek transfer learning konfigürasyonları:")
for config_key, (base_name, strategy, display_name) in transfer_configs.items():
    print(f"   📌 {display_name}")
print()

transfer_results = {}
transfer_times = {}
transfer_params = {}

for i, (config_key, (base_name, strategy, display_name)) in enumerate(transfer_configs.items()):
    print(f"🔄 Test {i+1}/{len(transfer_configs)}: {display_name}")

    try:
        # Model oluştur
        model = create_transfer_model(
            base_model_name=base_name,
            input_shape=IMG_SIZE + (3,),
            num_classes=num_classes,
            strategy=strategy
        )

        # Model bilgileri
        total_params = model.count_params()
        trainable_params = sum([tf.reduce_prod(var.shape) for var in model.trainable_variables])
        transfer_params[display_name] = {'total': total_params, 'trainable': trainable_params}

        print(f"   📊 Toplam parametre: {total_params:,}")
        print(f"   🎯 Eğitilebilir parametre: {trainable_params:,}")
        print(f"   ❄️ Dondurulmuş parametre: {total_params - trainable_params:,}")

        # Optimizer ayarları (strategy'ye göre)
        if strategy == 'feature_extraction':
            optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
        elif strategy == 'fine_tuning':
            optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)  # Daha düşük lr
        else:  # full_training
            optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)

        # Modeli derle
        model.compile(
            optimizer=optimizer,
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy']
        )

        # Eğitim
        start_time = time.time()

        # Epoch sayısı strategy'ye göre ayarla
        epochs = 3 if strategy == 'feature_extraction' else 5

        history = model.fit(
            train_ds,
            epochs=epochs,
            validation_data=val_ds,
            verbose=0
        )

        end_time = time.time()

        # Sonuçları kaydet
        transfer_results[display_name] = history.history
        transfer_times[display_name] = end_time - start_time

        final_val_acc = history.history['val_accuracy'][-1]
        training_time = end_time - start_time

        print(f"   ✅ Final Val Accuracy: %{final_val_acc*100:.2f}")
        print(f"   ⏰ Eğitim süresi: {training_time:.1f} saniye")
        print(f"   ⚡ Epoch başına: {training_time/epochs:.1f}s")
        print()

        # Memory temizliği
        del model
        K.clear_session()

    except Exception as e:
        print(f"   ❌ Hata: {str(e)[:100]}...")
        print()

print("🏁 Transfer learning testleri tamamlandı!")

import numpy as np
import matplotlib.pyplot as plt

# === 1. Grafik Fonksiyonu ===
def plot_transfer_learning_comparison(results, times, params):
    """
    Transfer learning sonuçlarını karşılaştıran grafikler
    """
    fig, axes = plt.subplots(3, 2, figsize=(16, 18))

    # 1. Validation Accuracy Comparison
    ax1 = axes[0, 0]
    colors = plt.cm.Set1(np.linspace(0, 1, len(results)))

    for i, (model_name, hist) in enumerate(results.items()):
        epochs = range(1, len(hist['val_accuracy']) + 1)
        ax1.plot(epochs, hist['val_accuracy'],
                label=model_name.replace(' (', '\n('),
                marker='o', linewidth=2, color=colors[i])

    ax1.set_title('🎯 Validation Accuracy Karşılaştırması', fontweight='bold')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Validation Accuracy')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    ax1.set_ylim(0, 1)

    # 2. Training Efficiency (Accuracy vs Time)
    ax2 = axes[0, 1]
    final_accuracies = [float(hist['val_accuracy'][-1]) for hist in results.values()]
    training_times = [float(v) for v in times.values()]

    for i, (name, acc, time_val) in enumerate(zip(results.keys(), final_accuracies, training_times)):
        ax2.scatter(time_val, acc, s=300, alpha=0.7,
                   color=colors[i], label=name.replace(' (', '\n('))
        ax2.annotate(name.split(' (')[0], (time_val, acc),
                    xytext=(5, 5), textcoords='offset points', fontsize=10)

    ax2.set_title('⚡ Eğitim Verimliliği (Acc vs Time)', fontweight='bold')
    ax2.set_xlabel('Eğitim Süresi (saniye)')
    ax2.set_ylabel('Final Validation Accuracy')
    ax2.grid(True, alpha=0.3)
    ax2.legend()

    # 3. Parameter Efficiency
    ax3 = axes[1, 0]
    model_names = list(results.keys())
    trainable_params = [int(params[name]['trainable']) for name in model_names]
    total_params = [int(params[name]['total']) for name in model_names]

    x_pos = np.arange(len(model_names))
    width = 0.35

    bars1 = ax3.bar(x_pos - width/2, [p/1e6 for p in total_params],
                    width, label='Toplam Parametre', alpha=0.7, color='lightblue')
    bars2 = ax3.bar(x_pos + width/2, [p/1e6 for p in trainable_params],
                    width, label='Eğitilebilir Parametre', alpha=0.7, color='orange')

    ax3.set_title('📊 Parametre Analizi (Milyon)', fontweight='bold')
    ax3.set_ylabel('Parametre Sayısı (Milyon)')
    ax3.set_xticks(x_pos)
    ax3.set_xticklabels([name.replace(' (', '\n(') for name in model_names], rotation=45, ha='right')
    ax3.legend()
    ax3.grid(True, alpha=0.3, axis='y')

    for bar1, bar2, total, trainable in zip(bars1, bars2, total_params, trainable_params):
        ax3.text(bar1.get_x() + bar1.get_width()/2., bar1.get_height() + 0.1,
                f'{total/1e6:.1f}M', ha='center', va='bottom', fontsize=9)
        ax3.text(bar2.get_x() + bar2.get_width()/2., bar2.get_height() + 0.1,
                f'{trainable/1e6:.1f}M', ha='center', va='bottom', fontsize=9)

    # 4. Learning Speed (First vs Last Epoch)
    ax4 = axes[1, 1]
    learning_improvements = []
    for model_name, hist in results.items():
        first_epoch_acc = float(hist['val_accuracy'][0])
        last_epoch_acc = float(hist['val_accuracy'][-1])
        improvement = last_epoch_acc - first_epoch_acc
        learning_improvements.append(improvement)

    colors_imp = ['green' if imp > 0.2 else 'orange' if imp > 0.1 else 'red'
                  for imp in learning_improvements]

    bars = ax4.bar(range(len(model_names)), learning_improvements,
                   color=colors_imp, alpha=0.7)
    ax4.set_title('📈 Öğrenme İyileştirmesi (İlk vs Son)', fontweight='bold')
    ax4.set_ylabel('Accuracy Artışı')
    ax4.set_xticks(range(len(model_names)))
    ax4.set_xticklabels([name.replace(' (', '\n(') for name in model_names], rotation=45, ha='right')

    for bar, imp in zip(bars, learning_improvements):
        height = bar.get_height()
        ax4.text(bar.get_x() + bar.get_width()/2., height + 0.005,
                f'{imp:.3f}', ha='center', va='bottom', fontweight='bold')
    ax4.grid(True, alpha=0.3)

    # 5. Model Complexity vs Performance
    ax5 = axes[2, 0]
    complexity_scores = [trainable/1e6 for trainable in trainable_params]

    for i, (name, acc, complexity) in enumerate(zip(model_names, final_accuracies, complexity_scores)):
        ax5.scatter(complexity, acc, s=300, alpha=0.7,
                   color=colors[i], label=name.replace(' (', '\n('))
        ax5.annotate(name.split(' (')[0], (complexity, acc),
                    xytext=(5, 5), textcoords='offset points', fontsize=10)

    ax5.set_title('🔬 Model Karmaşıklığı vs Performans', fontweight='bold')
    ax5.set_xlabel('Eğitilebilir Parametre (Milyon)')
    ax5.set_ylabel('Final Validation Accuracy')
    ax5.grid(True, alpha=0.3)
    ax5.legend()

    # 6. Strategy Comparison
    ax6 = axes[2, 1]
    feature_extraction_results, fine_tuning_results, fe_names, ft_names = [], [], [], []

    for name, hist in results.items():
        final_acc = float(hist['val_accuracy'][-1])
        if 'Feature Extraction' in name:
            feature_extraction_results.append(final_acc)
            fe_names.append(name.split(' (')[0])
        elif 'Fine-Tuning' in name:
            fine_tuning_results.append(final_acc)
            ft_names.append(name.split(' (')[0])

    base_models, fe_scores, ft_scores = [], [], []
    for fe_name, fe_score in zip(fe_names, feature_extraction_results):
        for ft_name, ft_score in zip(ft_names, fine_tuning_results):
            if fe_name == ft_name:
                base_models.append(fe_name)
                fe_scores.append(fe_score)
                ft_scores.append(ft_score)
                break

    if base_models:
        x_pos = np.arange(len(base_models))
        width = 0.35

        bars1 = ax6.bar(x_pos - width/2, fe_scores, width,
                       label='Feature Extraction', alpha=0.7, color='lightcoral')
        bars2 = ax6.bar(x_pos + width/2, ft_scores, width,
                       label='Fine-Tuning', alpha=0.7, color='lightgreen')

        ax6.set_title('🔄 Strateji Karşılaştırması', fontweight='bold')
        ax6.set_ylabel('Final Validation Accuracy')
        ax6.set_xticks(x_pos)
        ax6.set_xticklabels(base_models, rotation=45, ha='right')
        ax6.legend()
        ax6.grid(True, alpha=0.3, axis='y')
        ax6.set_ylim(0, 1)

        for bar1, bar2, fe_score, ft_score in zip(bars1, bars2, fe_scores, ft_scores):
            ax6.text(bar1.get_x() + bar1.get_width()/2., bar1.get_height() + 0.01,
                    f'{fe_score:.3f}', ha='center', va='bottom', fontsize=10, fontweight='bold')
            ax6.text(bar2.get_x() + bar2.get_width()/2., bar2.get_height() + 0.01,
                    f'{ft_score:.3f}', ha='center', va='bottom', fontsize=10, fontweight='bold')
    else:
        ax6.text(0.5, 0.5, 'Strateji karşılaştırması için\nyeterli data yok',
                ha='center', va='center', transform=ax6.transAxes, fontsize=12)
        ax6.set_title('🔄 Strateji Karşılaştırması', fontweight='bold')

    plt.tight_layout()
    plt.suptitle('🚀 Transfer Learning Karşılaştırması',
                 fontsize=16, fontweight='bold', y=0.98)
    plt.show()

# === 2. Analiz Raporu ===
def analyze_transfer_learning(results, times, params):
    print("📊 TRANSFER LEARNING ANALİZİ")
    print("=" * 60)

    best_transfer_model = ""
    best_transfer_performance = 0
    most_efficient_transfer = ""
    best_transfer_efficiency = 0

    for model_name, hist in results.items():
        final_val_acc = float(hist['val_accuracy'][-1])
        training_time = float(times[model_name])
        total_params = int(params[model_name]['total'])
        trainable_params = int(params[model_name]['trainable'])

        param_efficiency = final_val_acc / (trainable_params / 1e6) if trainable_params > 0 else 0
        time_efficiency = final_val_acc / (training_time / 60) if training_time > 0 else 0
        transfer_ratio = trainable_params / total_params if total_params > 0 else 0
        learning_improvement = float(hist['val_accuracy'][-1]) - float(hist['val_accuracy'][0])

        print(f"🚀 {model_name}:")
        print(f"   📊 Final Val Accuracy: %{final_val_acc*100:.2f}")
        print(f"   🧮 Toplam parametre: {total_params/1e6:.1f}M")
        print(f"   🎯 Eğitilebilir parametre: {trainable_params/1e6:.1f}M (%{transfer_ratio*100:.1f})")
        print(f"   ⏰ Eğitim süresi: {training_time:.1f} saniye")
        print(f"   ⚡ Parametre verimliliği: {param_efficiency:.2f}")
        print(f"   🚀 Zaman verimliliği: {time_efficiency:.2f}")
        print(f"   📈 Öğrenme iyileştirmesi: %{learning_improvement*100:.2f}")
        print()

        if final_val_acc > best_transfer_performance:
            best_transfer_performance = final_val_acc
            best_transfer_model = model_name
        if param_efficiency > best_transfer_efficiency:
            best_transfer_efficiency = param_efficiency
            most_efficient_transfer = model_name

    print("🏆 TRANSFER LEARNING SONUÇLARI:")
    print(f"   🥇 En İyi Performans: {best_transfer_model}")
    print(f"     📊 Accuracy: %{best_transfer_performance*100:.2f}")
    print(f"   ⚡ En Verimli Model: {most_efficient_transfer}")
    print(f"     🎯 Verimlilik: {best_transfer_efficiency:.2f}")
    print()

    print("💡 TRANSFER LEARNING REHBERİ:")
    print("   📱 MobileNetV2: Hafif, mobil uygulamalar için ideal")
    print("   🏛️ VGG16: Klasik, anlaşılır mimari, feature extraction'da iyi")
    print("   🔄 ResNet50: Derin ağlar, çok karmaşık özellikler")
    print("   ⚡ EfficientNet: SOTA performans, optimize edilmiş")
    print()
    print("   🎯 Feature Extraction: Az veri, hızlı eğitim")
    print("   🔧 Fine-Tuning: Daha fazla veri, daha iyi performans")
    print("   🚀 Full Training: Çok fazla veri, en iyi performans (pahalı)")

# === Kullanım ===
plot_transfer_learning_comparison(transfer_results, transfer_times, transfer_params)
analyze_transfer_learning(transfer_results, transfer_times, transfer_params)

"""# 📖 PART 8: Hyperparameter Tuning (Hiperparametre Optimizasyonu)
⚙️ Hiperparametreler Nedir?
Hiperparametreler, model mimarisini ve eğitim sürecini kontrol eden parametrelerdir. Model eğitimi sırasında öğrenilmez, önceden belirlenir.
Modeli eğitmeden önce bizim (insanların) belirlediği, modelin kendisinin öğrenmediği ayarlar. (Örnek: Öğrenme Oranı, Batch Boyutu, Katman sayısı).

🎛️ Ana Hiperparametre Kategorileri:

* **Model Mimarisi**

    Katman sayısı, nöron sayısı

  
    Aktivasyon fonksiyonları

  
    Dropout oranları


* **Eğitim Süreci**

    Learning rate, batch size

  
    Epoch sayısı, optimizer seçimi

  
    Loss fonksiyonu


* **Regularization**

    L1/L2 katsayıları

  
    Dropout değerleri

  
    Early stopping patience
"""

def create_tuning_model(config, input_shape, num_classes):
    """
    Hiperparametre konfigürasyonuna göre model oluşturur
    """
    model = models.Sequential([
        layers.Input(shape=input_shape),
        layers.Rescaling(1./255),
        layers.Flatten(),

        # İlk gizli katman
        layers.Dense(config['hidden_1'], activation=config['activation']),
        layers.Dropout(config['dropout_1']),

        # İkinci gizli katman (opsiyonel)
        layers.Dense(config['hidden_2'], activation=config['activation']),
        layers.Dropout(config['dropout_2']),

        # Çıkış katmanı
        layers.Dense(num_classes, activation='softmax')
    ], name=f"Tuned_Model")

    return model

print("⚙️ HİPERPARAMETRE TUNİNG KARŞILAŞTIRMASI")
print("=" * 60)

# Test edilecek hiperparametre konfigürasyonları
hyperparameter_configs = {
    'baseline': {
        'hidden_1': 128,
        'hidden_2': 64,
        'activation': 'relu',
        'dropout_1': 0.3,
        'dropout_2': 0.2,
        'learning_rate': 0.001,
        'batch_size': 32,
        'optimizer': 'adam'
    },
    'large_model': {
        'hidden_1': 256,
        'hidden_2': 128,
        'activation': 'relu',
        'dropout_1': 0.4,
        'dropout_2': 0.3,
        'learning_rate': 0.001,
        'batch_size': 32,
        'optimizer': 'adam'
    },
    'high_dropout': {
        'hidden_1': 128,
        'hidden_2': 64,
        'activation': 'relu',
        'dropout_1': 0.6,
        'dropout_2': 0.5,
        'learning_rate': 0.001,
        'batch_size': 32,
        'optimizer': 'adam'
    },
    'small_lr': {
        'hidden_1': 128,
        'hidden_2': 64,
        'activation': 'relu',
        'dropout_1': 0.3,
        'dropout_2': 0.2,
        'learning_rate': 0.0001,
        'batch_size': 32,
        'optimizer': 'adam'
    },
    'large_batch': {
        'hidden_1': 128,
        'hidden_2': 64,
        'activation': 'relu',
        'dropout_1': 0.3,
        'dropout_2': 0.2,
        'learning_rate': 0.002,  # Büyük batch için lr artırıldı
        'batch_size': 64,
        'optimizer': 'adam'
    },
    'tanh_activation': {
        'hidden_1': 128,
        'hidden_2': 64,
        'activation': 'tanh',
        'dropout_1': 0.3,
        'dropout_2': 0.2,
        'learning_rate': 0.001,
        'batch_size': 32,
        'optimizer': 'adam'
    }
}

print("🎯 Test edilecek konfigürasyonlar:")
for config_name, config in hyperparameter_configs.items():
    print(f"   📌 {config_name}: Hidden({config['hidden_1']}, {config['hidden_2']}), "
          f"LR({config['learning_rate']}), Batch({config['batch_size']})")
print()

tuning_results = {}
tuning_times = {}
tuning_configs = {}

for i, (config_name, config) in enumerate(hyperparameter_configs.items()):
    print(f"🔄 Test {i+1}/{len(hyperparameter_configs)}: {config_name}")

    # Model oluştur
    model = create_tuning_model(
        config=config,
        input_shape=IMG_SIZE + (3,),
        num_classes=num_classes
    )

    # Optimizer oluştur
    if config['optimizer'] == 'adam':
        optimizer = tf.keras.optimizers.Adam(learning_rate=config['learning_rate'])
    elif config['optimizer'] == 'sgd':
        optimizer = tf.keras.optimizers.SGD(learning_rate=config['learning_rate'])
    elif config['optimizer'] == 'rmsprop':
        optimizer = tf.keras.optimizers.RMSprop(learning_rate=config['learning_rate'])

    # Modeli derle
    model.compile(
        optimizer=optimizer,
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    # Batch size'a göre dataset'i yeniden oluştur (gerekirse)
    if config['batch_size'] != BATCH_SIZE:
        temp_train_ds = tf.keras.preprocessing.image_dataset_from_directory(
            processed_data_dir,
            validation_split=VALIDATION_SPLIT,
            subset="training",
            seed=RANDOM_SEED,
            image_size=IMG_SIZE,
            batch_size=config['batch_size'],
            label_mode='int'
        ).cache().prefetch(AUTOTUNE)

        temp_val_ds = tf.keras.preprocessing.image_dataset_from_directory(
            processed_data_dir,
            validation_split=VALIDATION_SPLIT,
            subset="validation",
            seed=RANDOM_SEED,
            image_size=IMG_SIZE,
            batch_size=config['batch_size'],
            label_mode='int'
        ).cache().prefetch(AUTOTUNE)
    else:
        temp_train_ds = train_ds
        temp_val_ds = val_ds

    # Eğitim
    start_time = time.time()
    history = model.fit(
        temp_train_ds,
        epochs=4,  # Hızlı karşılaştırma için
        validation_data=temp_val_ds,
        verbose=0
    )
    end_time = time.time()

    # Sonuçları kaydet
    tuning_results[config_name] = history.history
    tuning_times[config_name] = end_time - start_time
    tuning_configs[config_name] = config

    final_val_acc = history.history['val_accuracy'][-1]
    training_time = end_time - start_time

    print(f"   ✅ Final Val Accuracy: %{final_val_acc*100:.2f}")
    print(f"   ⏰ Eğitim süresi: {training_time:.1f} saniye")
    print(f"   📊 Parametre sayısı: {model.count_params():,}")
    print()

    # Memory temizliği
    del model
    if config['batch_size'] != BATCH_SIZE:
        del temp_train_ds, temp_val_ds
    K.clear_session()

print("🏁 Hiperparametre tuning testleri tamamlandı!")

import matplotlib.pyplot as plt
import numpy as np

def plot_tuning_comparison(results, times, configs):
    """
    Hiperparametre tuning sonuçlarını karşılaştıran grafikler.
    """
    fig, axes = plt.subplots(2, 2, figsize=(14, 12))

    model_names = list(results.keys())
    colors = plt.cm.tab10(np.linspace(0, 1, len(model_names)))

    # 1. Validation Accuracy Comparison
    ax1 = axes[0, 0]
    for i, model_name in enumerate(model_names):
        epochs = range(1, len(results[model_name]['val_accuracy']) + 1)
        ax1.plot(epochs, results[model_name]['val_accuracy'],
                 label=model_name, marker='o', linewidth=2, color=colors[i])

    ax1.set_title('🎯 Validation Accuracy Karşılaştırması', fontweight='bold')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Validation Accuracy')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    ax1.set_ylim(0, 1)

    # 2. Training Efficiency (Accuracy vs Time)
    ax2 = axes[0, 1]
    final_accuracies = [float(results[name]['val_accuracy'][-1]) for name in model_names]
    training_times = [float(times[name]) for name in model_names]

    for i, (name, acc, time_val) in enumerate(zip(model_names, final_accuracies, training_times)):
        ax2.scatter(time_val, acc, s=300, alpha=0.7, color=colors[i], label=name)
        ax2.annotate(name, (time_val, acc), xytext=(5, 5), textcoords='offset points', fontsize=9)

    ax2.set_title('⚡ Eğitim Verimliliği (Acc vs Time)', fontweight='bold')
    ax2.set_xlabel('Eğitim Süresi (saniye)')
    ax2.set_ylabel('Final Validation Accuracy')
    ax2.grid(True, alpha=0.3)
    ax2.legend()

    # 3. Parametre Sayısı Karşılaştırması
    ax3 = axes[1, 0]
    param_counts = [configs[name]['hidden_1']*configs[name]['hidden_2'] + configs[name]['hidden_2']*len(results[name]['val_accuracy']) for name in model_names]
    bars = ax3.bar(model_names, param_counts, color=colors, alpha=0.7)

    ax3.set_title('📊 Parametre Sayısı Karşılaştırması', fontweight='bold')
    ax3.set_ylabel('Parametre Sayısı')
    ax3.grid(True, axis='y', alpha=0.3)

    for bar, param_count in zip(bars, param_counts):
        ax3.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 0.05*max(param_counts),
                 f"{param_count:,}", ha='center', va='bottom', fontsize=9)

    # 4. Learning Improvement (Final - İlk Epoch)
    ax4 = axes[1, 1]
    learning_improvements = [
        float(results[name]['val_accuracy'][-1]) - float(results[name]['val_accuracy'][0])
        for name in model_names
    ]
    bars = ax4.bar(model_names, learning_improvements, color=colors, alpha=0.7)

    ax4.set_title('📈 Öğrenme İyileştirmesi (Final - İlk Epoch)', fontweight='bold')
    ax4.set_ylabel('Accuracy Artışı')
    ax4.grid(True, axis='y', alpha=0.3)

    for bar, improvement in zip(bars, learning_improvements):
        ax4.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 0.005,
                 f"{improvement:.3f}", ha='center', va='bottom', fontsize=9)

    plt.tight_layout()
    plt.suptitle('🚀 Hiperparametre Tuning Karşılaştırması', fontsize=16, fontweight='bold', y=1.02)
    plt.show()
def analyze_tuning_results(results, times, configs):
    print("📊 HİPERPARAMETRE TUNING ANALİZİ")
    print("=" * 60)

    best_model = ""
    best_acc = 0
    fastest_model = ""
    best_efficiency = 0

    for name in results.keys():
        final_val_acc = float(results[name]['val_accuracy'][-1])
        first_val_acc = float(results[name]['val_accuracy'][0])
        training_time = float(times[name])
        improvement = final_val_acc - first_val_acc
        efficiency = final_val_acc / training_time if training_time > 0 else 0

        print(f"🔹 {name}:")
        print(f"   📊 Final Val Accuracy: %{final_val_acc*100:.2f}")
        print(f"   ⏰ Eğitim süresi: {training_time:.1f} saniye")
        print(f"   📈 Öğrenme iyileştirmesi: %{improvement*100:.2f}")
        print(f"   ⚡ Verimlilik (Acc/Süre): {efficiency:.4f}")
        print()

        if final_val_acc > best_acc:
            best_acc = final_val_acc
            best_model = name
        if efficiency > best_efficiency:
            best_efficiency = efficiency
            fastest_model = name

    print("🏆 SONUÇLAR:")
    print(f"   🥇 En iyi model: {best_model} (%{best_acc*100:.2f})")
    print(f"   ⚡ En verimli model: {fastest_model} (Efficiency: {best_efficiency:.4f})")
plot_tuning_comparison(tuning_results, tuning_times, tuning_configs)
analyze_tuning_results(tuning_results, tuning_times, tuning_configs)





